export default {
  ARTIFICIAL_SELECT_TILE: 'ARTIFICIAL_SELECT_TILE',
  CHANGE_RULES: 'CHANGE_RULES',
  INIT_GAME: 'INIT_GAME',
  PAUSE_BOARD: 'PAUSE_BOARD',
  SELECT_TILE: 'SELECT_TILE',
  TOGGLE_AI: 'TOGGLE_AI',
  WON_BOARD: 'WON_BOARD'
};
